### PR TITLE
prjoxide: add debian/buster dockerfile

### PR DESCRIPTION
**Pull request by umarcor**
Ref #35.

@tcal-x, this is an attempt at building prjoxide on a Debian Buster container. I used https://github.com/gatecat/prjoxide#building-the-prjoxide-tool as a reference.

The build is failing: `undefined reference to llvm.x86.addcarry.64` (https://github.com/hdl/containers/runs/3093067566?check_suite_focus=true#step:4:296). In https://github.com/librespot-org/librespot/issues/555, they fixed it by adding a `Cargo.lock` file, but I don't know if that can be done in prjoxide.

/cc @gatecat

### CODE REVIEW

**Comment by mithro** [comment]
Ping - @tcal

**Comment by tcal-x** [comment]
Hi @umarcor , thank you for this PR and the investigation into the error!   I tried adding `--locked` to the `cargo install` command, but it did not change the outcome for me.   But maybe I was misunderstanding the fixes suggested in the links you found.

**Comment by umarcor** [comment]
@tcal-x my understanding is that `--locked` in Cargo might be similar to `requirements.txt` files in Python, `go.mod` in Golang, etc. That is, it requires a file upstream (in prjoxide) where the dependencies are pinned. See https://github.com/librespot-org/librespot/blob/dev/Cargo.lock in the project referenced above.

**Comment by umarcor** [comment]
There seems not to be problems on Debian Bullseye, so I pushed that to main. This PR is now for tracking the addition of the Debian Buster dockerfile.

**Comment by tcal-x** [comment]
Thanks @umarcor !

**Comment by umarcor** [comment]
FTR, nextpnr/nexus and nextpnr/prjoxide images are available now.

**Comment by umarcor** [comment]
Collection Debian Buster was deprecated.

**Pull request closed without merging**
